<?php

namespace AppBundle\Repository;

/**
 * galleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class galleryRepository extends \Doctrine\ORM\EntityRepository
{
}
