<?php

namespace AppBundle\Repository;

/**
 * reviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewsRepository extends \Doctrine\ORM\EntityRepository
{
}
