<?php

namespace AppBundle\Repository;

/**
 * serviciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serviciosRepository extends \Doctrine\ORM\EntityRepository
{
}
