# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    encoders:
        AppBundle\Entity\user:
            algorithm: bcrypt
    providers:
        user:
            entity:
              class: AppBundle:user
              property: username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                  login_path: login
                  check_path: login
                  default_target_path: admin_banner_index
                  always_use_default_target_path: true
            logout:
                  path: logout
                  target: homepage
            provider: user

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
